export const welcome = [
	`Ready for baking some cookies?`,
	`Today I'm in a good mood, I could give you some cookies.`,
	`I'm here to help you with your projects!`,
	`Your friendly cookie baker is here!`,
	`Let's cook something together!`,
	`With my help, you can bake something.`,
	`Making projects never been so fun and easy!`,
	`Oh... you lost your tools? Don't worry, I can help you!`,
	`Let's create a new project!`,
	`Let the cooking begin!`,
	`Time to cook something new.`,
	`New project incoming!`,
	`Time to do a project sweet as my cookie.`,
	`How do you got here?`,
	`Putting the oven to temperature!`,
	`Haru will help you with anything!`,
	`Watching the oven for baking cookies...`,
	`Help is on the way!`,
];